// <auto-generated />
using System;
using AspNetExample.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspNetExample.Database.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250329134223_AddInternProfessorIndexes")]
    partial class AddInternProfessorIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspNetExample.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Building")
                        .HasColumnType("int");

                    b.Property<decimal>("Financing")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("money")
                        .HasDefaultValue(0m);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departments", t =>
                        {
                            t.HasCheckConstraint("CK_Departments_Building", "Building BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_Departments_Financing", "Financing >= 0");

                            t.HasCheckConstraint("CK_Departments_Name", "LEN(Name) > 0");
                        });
                });

            modelBuilder.Entity("AspNetExample.Domain.Entities.Disease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Diseases", t =>
                        {
                            t.HasCheckConstraint("CK_Diseases_Name", "LEN(Name) > 0");
                        });
                });

            modelBuilder.Entity("AspNetExample.Domain.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("money");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Doctors", t =>
                        {
                            t.HasCheckConstraint("CK_Doctors_Name", "LEN(Name) > 0");

                            t.HasCheckConstraint("CK_Doctors_Salary", "Salary > 0");

                            t.HasCheckConstraint("CK_Doctors_Surname", "LEN(Surname) > 0");
                        });
                });

            modelBuilder.Entity("AspNetExample.Domain.Entities.DoctorExamination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("DiseaseId")
                        .HasColumnType("int");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("ExaminationId")
                        .HasColumnType("int");

                    b.Property<int>("WardId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DiseaseId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("ExaminationId");

                    b.HasIndex("WardId");

                    b.ToTable("DoctorsExaminations", t =>
                        {
                            t.HasCheckConstraint("CK_DoctorsExaminations_Date", "Date <= GETDATE()");
                        });
                });

            modelBuilder.Entity("AspNetExample.Domain.Entities.Examination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Examinations", t =>
                        {
                            t.HasCheckConstraint("CK_Examinations_Name", "LEN(Name) > 0");
                        });
                });

            modelBuilder.Entity("AspNetExample.Domain.Entities.Intern", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId")
                        .IsUnique();

                    b.ToTable("Interns");
                });

            modelBuilder.Entity("AspNetExample.Domain.Entities.Professor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId")
                        .IsUnique();

                    b.ToTable("Professors");
                });

            modelBuilder.Entity("AspNetExample.Domain.Entities.Ward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Places")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Wards", t =>
                        {
                            t.HasCheckConstraint("CK_Wards_Name", "LEN(Name) > 0");

                            t.HasCheckConstraint("CK_Wards_Places", "Places > 0");
                        });
                });

            modelBuilder.Entity("AspNetExample.Domain.Entities.DoctorExamination", b =>
                {
                    b.HasOne("AspNetExample.Domain.Entities.Disease", "Disease")
                        .WithMany("DoctorsExaminations")
                        .HasForeignKey("DiseaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetExample.Domain.Entities.Doctor", "Doctor")
                        .WithMany("DoctorsExaminations")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetExample.Domain.Entities.Examination", "Examination")
                        .WithMany("DoctorsExaminations")
                        .HasForeignKey("ExaminationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetExample.Domain.Entities.Ward", "Ward")
                        .WithMany("DoctorsExaminations")
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Disease");

                    b.Navigation("Doctor");

                    b.Navigation("Examination");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("AspNetExample.Domain.Entities.Intern", b =>
                {
                    b.HasOne("AspNetExample.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Interns")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("AspNetExample.Domain.Entities.Professor", b =>
                {
                    b.HasOne("AspNetExample.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Professors")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("AspNetExample.Domain.Entities.Ward", b =>
                {
                    b.HasOne("AspNetExample.Domain.Entities.Department", "Department")
                        .WithMany("Wards")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("AspNetExample.Domain.Entities.Department", b =>
                {
                    b.Navigation("Wards");
                });

            modelBuilder.Entity("AspNetExample.Domain.Entities.Disease", b =>
                {
                    b.Navigation("DoctorsExaminations");
                });

            modelBuilder.Entity("AspNetExample.Domain.Entities.Doctor", b =>
                {
                    b.Navigation("DoctorsExaminations");

                    b.Navigation("Interns");

                    b.Navigation("Professors");
                });

            modelBuilder.Entity("AspNetExample.Domain.Entities.Examination", b =>
                {
                    b.Navigation("DoctorsExaminations");
                });

            modelBuilder.Entity("AspNetExample.Domain.Entities.Ward", b =>
                {
                    b.Navigation("DoctorsExaminations");
                });
#pragma warning restore 612, 618
        }
    }
}
